server:
  port: 11120

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yunjiaoyang/abba-microservices
          search-paths: config-repo
          clone-on-start: true
  security:
    user:
      name: admin
      password: abba
